export type ClientEvent = ""
| "chat-message"
| "create-room"
| "join-room"
| "leave-room"
| "create-dm-room"
| "leave-dm-room"
| "create-game"
| "join-game"
| "leave-game"
| "join-game-as-observateur"
| "leave-game-as-observateur"
| "replace-bot-by-observer"
| "start-game"
| "playMove"
| "indice";