export type ServerEvent = "listUsers"
| "joinedRoom"
| "gameUpdate"
| "chat-message"
| "joinableGames"
| "listChatRooms"
| "timerUpdate"
| "userJoined"
| "error"
| "indice"
| "newUser"
| "friendRequest"
| "acceptFriendRequest"
| "declineFriendRequest";
