version: "3"

tasks:
  dev:
    cmds:
      - watchexec -r -c -e go -- go run main.go
  build:
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags '-s -w' -o bin/out
  start:
    cmds:
      - ./bin/out