import { Injectable } from "@angular/core";
import { Square } from "@app/utils/interfaces/square";

@Injectable({
    providedIn: 'root',
})
export class BoardHelper {
    static createBoard(): Square[][] {
        return [
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 3 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 2, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
            ],
            [
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 2 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 1, letterMultiplier: 1 },
                { piece: {letter: "", value: 0}, wordMultiplier: 3, letterMultiplier: 1 },
            ]
        ];
    }
}